In [1]:
# Base class
from src.Base.Config import Config

# Project class
from src.BetaMouv.Trajectory import TrajectoryDLC, DLCTracking
import src.BetaMouv.Behavior as Behavior
import src.utils as u

# other lib
from pathlib import Path
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

### Load project from config

In [2]:
cfg = Config(Path("./config.yaml"))
project = cfg.load_project()

log: config unchanged (config_20261026_160123.yaml)

 CONTRA_CHR_#517_#525_#521_#531

### Setup analysis dir

In [3]:
custom_params = {"axes.spines.right": False, "axes.spines.top": False}
sns.set_theme("talk", style="ticks", rc=custom_params, palette="pastel")

analysis_dir = u.make_dir(project.paths.analysis(project.trialgroup.keep_val))
df_dir = u.make_dir(analysis_dir / "trials_df")

Some hypper parameters

In [4]:
project.trialgroup.crop_laser_period = True
project.trialgroup.remove_NOstim = True

In [ ]:
project.trialgroup.load_trials()

In [ ]:
traj_data = []

n=0
for trial in project.trialgroup.trials:
    if not trial.is_valid():
        continue

    for bp, stat in trial.trajectories.items():
        data = {info: val for  info, val in stat.items()}
        data["id"] = n
        data["trial_name"] = trial.name

        traj_data.append(data)


traj_data_df = pd.DataFrame(traj_data)
traj_data_df.to_csv("traj_data_df.csv")

In [5]:
project.trialgroup.build_df(df_dir, "trial_success")
project.trialgroup.build_df(df_dir, "bodypart_success")

'trial_success' already exist: 'data/BetaMouv/results/CONTRA_CHR_#517_#525_#521_#531/trials_df/trial_success.csv'
Loading...

'bodypart_success' already exist: 'data/BetaMouv/results/CONTRA_CHR_#517_#525_#521_#531/trials_df/bodypart_success.csv'
Loading...

,name,clip_path,date,camera_view,clip_number,laser_intensity,handedness,laser_type,subject,condition,...,time_pad_off,time_laser_on,time_reward,group,trial_outcomes,camera_shift,bodypart,stage,success,reason
0,Rat_#517Ambidexter_20240705_BetaMT300_RightHem...,data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...,2024-07-05,left,7,high,Ambidexter,Beta,#517,CHR,...,0.272,0.296,0.552,#517_CHR_CONTRA_Beta_RightHemi_leftView_high_L...,{'clip_openable': Outcome(stage='clip_openable...,"(0.046, 0.023)",Hand_base,outlier,True,0 out
1,Rat_#517Ambidexter_20240705_BetaMT300_RightHem...,data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...,2024-07-05,left,7,high,Ambidexter,Beta,#517,CHR,...,0.272,0.296,0.552,#517_CHR_CONTRA_Beta_RightHemi_leftView_high_L...,{'clip_openable': Outcome(stage='clip_openable...,"(0.046, 0.023)",Hand_base,validation,True,0 out
2,Rat_#517Ambidexter_20240705_BetaMT300_RightHem...,data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...,2024-07-05,left,7,high,Ambidexter,Beta,#517,CHR,...,0.272,0.296,0.552,#517_CHR_CONTRA_Beta_RightHemi_leftView_high_L...,{'clip_openable': Outcome(stage='clip_openable...,"(0.046, 0.023)",Base_finger_2,outlier,True,0 out
3,Rat_#517Ambidexter_20240705_BetaMT300_RightHem...,data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...,2024-07-05,left,7,high,Ambidexter,Beta,#517,CHR,...,0.272,0.296,0.552,#517_CHR_CONTRA_Beta_RightHemi_leftView_high_L...,{'clip_openable': Outcome(stage='clip_openable...,"(0.046, 0.023)",Base_finger_2,validation,True,0 out
4,Rat_#517Ambidexter_20240705_BetaMT300_RightHem...,data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...,2024-07-05,left,7,high,Ambidexter,Beta,#517,CHR,...,0.272,0.296,0.552,#517_CHR_CONTRA_Beta_RightHemi_leftView_high_L...,{'clip_openable': Outcome(stage='clip_openable...,"(0.046, 0.023)",Base_finger_3,outlier,True,0 out
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70807,Rat_#521RightHanded_20240528_Session1_ContiMT3...,data/BetaMouv/raw/subject_#521/Rat_#521RightHa...,2024-05-28,right,21,low,RightHanded,Conti,#521,CHR,...,0.280,0.304,NaN,#521_CHR_CONTRA_Conti_LeftHemi_rightView_low_L...,{'clip_openable': Outcome(stage='clip_openable...,"(-0.418, -1.113)",Lever_ball,validation,True,few out
70808,Rat_#521RightHanded_20240528_Session1_ContiMT3...,data/BetaMouv/raw/subject_#521/Rat_#521RightHa...,2024-05-28,right,21,low,RightHanded,Conti,#521,CHR,...,0.280,0.304,NaN,#521_CHR_CONTRA_Conti_LeftHemi_rightView_low_L...,{'clip_openable': Outcome(stage='clip_openable...,"(-0.418, -1.113)",Lever_base,outlier,False,out cons>5
70809,Rat_#521RightHanded_20240528_Session1_ContiMT3...,data/BetaMouv/raw/subject_#521/Rat_#521RightHa...,2024-05-28,right,21,low,RightHanded,Conti,#521,CHR,...,0.280,0.304,NaN,#521_CHR_CONTRA_Conti_LeftHemi_rightView_low_L...,{'clip_openable': Outcome(stage='clip_openable...,"(-0.418, -1.113)",Lever_base,validation,False,out cons>5
70810,Rat_#521RightHanded_20240528_Session1_ContiMT3...,data/BetaMouv/raw/subject_#521/Rat_#521RightHa...,2024-05-28,right,21,low,RightHanded,Conti,#521,CHR,...,0.280,0.304,NaN,#521_CHR_CONTRA_Conti_LeftHemi_rightView_low_L...,{'clip_openable': Outcome(stage='clip_openable...,"(-0.418, -1.113)",Lever_corner,outlier,True,few out
70811,Rat_#521RightHanded_20240528_Session1_ContiMT3...,data/BetaMouv/raw/subject_#521/Rat_#521RightHa...,2024-05-28,right,21,low,RightHanded,Conti,#521,CHR,...,0.280,0.304,NaN,#521_CHR_CONTRA_Conti_LeftHemi_rightView_low_L...,{'clip_openable': Outcome(stage='clip_openable...,"(-0.418, -1.113)",Lever_corner,validation,True,few out

In [6]:
project.trialgroup.trial_success_rate(u.make_path(analysis_dir, "trial_success_rate.png"))

Report saved to: data/BetaMouv/results/CONTRA_CHR_#517_#525_#521_#531/trial_success_rate.png

In [7]:
project.trialgroup.trajectories_success_rate(u.make_path(analysis_dir, "trajectories_success_rate.png"))

Report saved to: data/BetaMouv/results/CONTRA_CHR_#517_#525_#521_#531/trajectories_success_rate.png

In [ ]:

project.trialgroup.sunburst_metadata(output_dir=u.make_dir(analysis_dir / "metadata_sunburst"),
                                  subfig_group="subject", 
                                  groups=["laser_type"],
                                  title=project.trialgroup.group_name)

In [ ]:
project.trialgroup.sunburst_metadata(output_dir=u.make_dir(analysis_dir / "metadata_sunburst"), 
                                  subfig_group="condition", 
                                  groups=["subject", "laser_type", "laser_intensity"],
                                  title=project.trialgroup.group_name)

In [ ]:
project.trialgroup.sunburst_metadata(output_dir=u.make_dir(analysis_dir / "metadata_sunburst"), 
                                  subfig_group=None, 
                                  groups=["subject", "is_valid", "failing_step"],
                                  title=project.trialgroup.group_name)

## Behavior analysis

In [5]:
project.trialgroup.build_df(df_dir, "behavior")
features = [
            "relative_t",
            "x", 
            "y",
            "area", 
            "centroid_direction", 
            "centroid_velocity", 
            "centroid_speed", 
            "centroid_acc", 
            "f3_sp_distance", 
            "f3_sp_angle", 
            "centroid_lever_dist"
]

'behavior' already exist: 'data/BetaMouv/results/CONTRA_CHR_#517_#525_#521_#531/trials_df/behavior.csv'
Loading...

In [8]:
for feat in features: 
    project.trialgroup.plot_tendency_beha_features(
                        save_as=u.make_path(analysis_dir / "behavior" / "with_behavior_span", f"{feat}.png"),
                        x="relative_t", y=feat, show_beha="spatial_behavior")

    project.trialgroup.plot_tendency_beha_features(
                        save_as=u.make_path(analysis_dir / "behavior", f"{feat}.png"),
                        x="relative_t", y=feat, show_beha=None)

In [9]:
project.trialgroup.lineplot_traj_centroid(save_as=u.make_path(analysis_dir / "behavior", f"centroid_traj.png"),)

Distribution of each features, per protocols

In [ ]:
for l_type in ["Beta","Conti"] : 
    for l_intensity in ["low", "high"]: 
        for l_state in ["LaserOn", "LaserOff"] : 
            project.trialgroup.distri_feat_per_behavior(behavior_varname="spatial_behavior", laser_type=l_type, laser_intensity=l_intensity, laser_state=l_state,
                                                    save_as=u.make_path(analysis_dir / "behavior" / "distri_feat_per_behavior", f"spatial_behavior_{l_type}_{l_intensity}_{l_state}.svg"),
                                                    features_list=features)

            project.trialgroup.distri_feat_per_behavior(behavior_varname="pred_state", laser_type=l_type, laser_intensity=l_intensity, laser_state=l_state,
                                                    save_as=u.make_path(analysis_dir / "behavior" / "distri_feat_per_behavior", f"HMM_pred_state_{l_type}_{l_intensity}_{l_state}.svg"),
                                                    features_list=features)

Distribution of each features, for the whole dataset

In [11]:
project.trialgroup.distri_feat_per_behavior(behavior_varname="spatial_behavior",
                                        save_as=u.make_path(analysis_dir / "behavior" / "distri_feat_per_behavior", "spatial_behavior_state_all.svg"),
                                        features_list=features)

/home/poemiti/anaconda3/envs/kinematics/lib/python3.10/site-packages/seaborn/axisgrid.py:123: UserWarning: Tight layout not applied. tight_layout cannot make Axes height small enough to accommodate all Axes decorations.
  self._figure.tight_layout(*args, **kwargs)
/home/poemiti/anaconda3/envs/kinematics/lib/python3.10/site-packages/seaborn/axisgrid.py:123: UserWarning: Tight layout not applied. tight_layout cannot make Axes height small enough to accommodate all Axes decorations.
  self._figure.tight_layout(*args, **kwargs)

Behavior exploration : HMM fitting

In [6]:
df = project.trialgroup._behavior_df
Behavior.HMM_exploration(df, analysis_dir, init=False)

UnboundLocalError: local variable 'save_path' referenced before assignment

In [ ]:
project.trialgroup.distri_feat_per_behavior(behavior_varname="pred_state", 
                                        save_as=u.make_path(analysis_dir / "behavior" / "distri_feat_per_behavior", "HMM_pred_state_all.svg"),
                                        features_list=features)

In [ ]:
for l_type in ["Beta","Conti"] : 
    for l_intensity in ["low", "high"]: 
        for l_state in ["LaserOn", "LaserOff"] : 
            project.trialgroup.distri_feat_per_behavior(behavior_varname="pred_state", laser_type=l_type, laser_intensity=l_intensity, laser_state=l_state,
                                                    save_as=u.make_path(analysis_dir / "behavior" / "distri_feat_per_behavior", f"HMM_pred_state_{l_type}_{l_intensity}_{l_state}.svg"),
                                                    features_list=features)

## Trajectory analysis

In [5]:
project.trialgroup.build_df(df_dir, "kinematics")

'kinematics' already exist: 'data/BetaMouv/results/CONTRA_CHR_#517_#525_#521_#531/trials_df/kinematics.csv'
Loading...

                                                    trial  \
                                                     name
0       Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
1       Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
2       Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
3       Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
4       Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
...                                                   ...
797803  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797804  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797805  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797806  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797807  Rat_#521RightHanded_20240528_Session1_ContiMT3...

                                                                       \
                                                clip_path        date
0       data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
1       data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
2       data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
3       data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
4       data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
...                                                   ...         ...
797803  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797804  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797805  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797806  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797807  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28

                                                                        \
       camera_view clip_number laser_intensity   handedness laser_type
0             left           7            high   Ambidexter       Beta
1             left           7            high   Ambidexter       Beta
2             left           7            high   Ambidexter       Beta
3             left           7            high   Ambidexter       Beta
4             left           7            high   Ambidexter       Beta
...            ...         ...             ...          ...        ...
797803       right          21             low  RightHanded      Conti
797804       right          21             low  RightHanded      Conti
797805       right          21             low  RightHanded      Conti
797806       right          21             low  RightHanded      Conti
797807       right          21             low  RightHanded      Conti

                          ...     Lever_corner                            \
       subject condition  ... instant_velocity instant_speed       angle
0         #517       CHR  ...              NaN           NaN         NaN
1         #517       CHR  ...        -0.129349      0.129349 -104.036243
2         #517       CHR  ...         0.255903      0.255903   24.928061
3         #517       CHR  ...        -0.881387      0.881387  100.903342
4         #517       CHR  ...        -0.498476      0.498476 -131.584171
...        ...       ...  ...              ...           ...         ...
797803    #521       CHR  ...        -0.074673      0.074673  -57.996265
797804    #521       CHR  ...        -0.028539      0.028539  -56.321216
797805    #521       CHR  ...        -0.060295      0.060295 -113.196062
797806    #521       CHR  ...        -0.080713      0.080713 -168.706994
797807    #521       CHR  ...        -0.015806      0.015806   90.000000

                                                          finger_2   finger_1  \
       lever_distance distances         acc  signed_acc likelihood likelihood
0            0.332747       NaN         NaN         NaN        NaN        NaN
1            0.333666  0.001035         NaN         NaN        NaN        NaN
2            0.331793  0.002047   43.989972   48.156519        NaN        NaN
3            0.327509  0.007051  107.019977 -142.161213        NaN        NaN
4            0.331497  0.003988  156.144603   47.863821        NaN        NaN
...               ...       ...         ...         ...        ...        ...
797803       6.104367  0.000597    4.946870   -4.909549        NaN        NaN
797804       6.104490  0.000228    5.769252    5.766785        NaN        NaN
797805       6.104291  0.000482    6.336033   -3.969530        NaN        NaN
797806       6.103655  0.000646    8.513448   -2.552168        NaN        NaN
797807       6.103658  0.000126   10.653625    8.113369        NaN        NaN

         finger_3
       likelihood
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
797803        NaN
797804        NaN
797805        NaN
797806        NaN
797807        NaN

[797808 rows x 164 columns]

In [11]:
timeseries_metric = [
                    "x", 
                    "y", 
                    "instant_velocity", 
                    "instant_speed", 
                    "acc", 
                    "signed_acc", 
                    "lever_distance",
                    "angle"
                    ]

bodypart = "finger_3" 
project.trialgroup.remove_NOstim = True
project.trialgroup.crop_laser_period = True

In [13]:
data = project.trialgroup._kinematics_df

if project.trialgroup.remove_NOstim:
    print("remove NOstim")
    data = data[data["trial"]["laser_type"] != "NOstim"]

if project.trialgroup.crop_laser_period:
    print("crop laser")
    t = data["trial"]["relative_t"]
    laser_on = data["trial"]["time_laser_on"]

    data = data[
        (t >= laser_on - 0.1) &
        (t <= laser_on + 0.325)
    ]
data

remove NOstim
crop laser

                                                    trial  \
                                                     name
59      Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
60      Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
61      Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
62      Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
63      Rat_#517Ambidexter_20240705_BetaMT300_RightHem...
...                                                   ...
797670  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797671  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797672  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797673  Rat_#521RightHanded_20240528_Session1_ContiMT3...
797674  Rat_#521RightHanded_20240528_Session1_ContiMT3...

                                                                       \
                                                clip_path        date
59      data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
60      data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
61      data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
62      data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
63      data/BetaMouv/raw/subject_#517/Rat_#517Ambidex...  2024-07-05
...                                                   ...         ...
797670  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797671  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797672  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797673  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28
797674  data/BetaMouv/raw/subject_#521/Rat_#521RightHa...  2024-05-28

                                                                        \
       camera_view clip_number laser_intensity   handedness laser_type
59            left           7            high   Ambidexter       Beta
60            left           7            high   Ambidexter       Beta
61            left           7            high   Ambidexter       Beta
62            left           7            high   Ambidexter       Beta
63            left           7            high   Ambidexter       Beta
...            ...         ...             ...          ...        ...
797670       right          21             low  RightHanded      Conti
797671       right          21             low  RightHanded      Conti
797672       right          21             low  RightHanded      Conti
797673       right          21             low  RightHanded      Conti
797674       right          21             low  RightHanded      Conti

                          ...     Lever_corner                            \
       subject condition  ... instant_velocity instant_speed       angle
59        #517       CHR  ...        -0.835637      0.835637  -83.157863
60        #517       CHR  ...        -0.549422      0.549422  -75.123515
61        #517       CHR  ...        -0.472726      0.472726  -79.380756
62        #517       CHR  ...        -1.059913      1.059913 -105.667942
63        #517       CHR  ...        -0.831400      0.831400 -105.631534
...        ...       ...  ...              ...           ...         ...
797670    #521       CHR  ...         0.145965      0.145965   49.396980
797671    #521       CHR  ...        -0.040340      0.040340  -11.326866
797672    #521       CHR  ...        -0.136671      0.136671  -10.006996
797673    #521       CHR  ...        -0.128863      0.128863  -47.479037
797674    #521       CHR  ...        -0.040356      0.040356  -78.706994

                                                          finger_2   finger_1  \
       lever_distance distances         acc  signed_acc likelihood likelihood
59           0.390353  0.006685  134.203811 -147.778858        NaN        NaN
60           0.392799  0.004395   37.693746   35.776960        NaN        NaN
61           0.395157  0.003782   10.691297    9.586920        NaN        NaN
62           0.402861  0.008479   83.705147  -73.398306        NaN        NaN
63           0.408925  0.006651   28.564129   28.564031        NaN        NaN
...               ...       ...         ...         ...        ...        ...
797670       6.107546  0.001168   15.987492   24.262417        NaN        NaN
797671       6.107861  0.000323   16.381274  -23.288175        NaN        NaN
797672       6.108933  0.001093   12.043164  -12.041266        NaN        NaN
797673       6.109614  0.001031   10.701433    0.975956        NaN        NaN
797674       6.109671  0.000323   12.080706   11.063323        NaN        NaN

         finger_3
       likelihood
59            NaN
60            NaN
61            NaN
62            NaN
63            NaN
...           ...
797670        NaN
797671        NaN
797672        NaN
797673        NaN
797674        NaN

[32037 rows x 164 columns]

In [15]:
for val in timeseries_metric:
    project.trialgroup.plot_tendency_metrics(
        value=val,
        save_as=u.make_path(analysis_dir / "tendency" / bodypart, f"{val}.svg"),
        # show_units=True, 
        show_beha=None
    )

Lineplot traj with behavior boxes

In [ ]:
trial = project.trialgroup.trials[1]
behavior_obj = Behavior(trial.trajectories, trial.time_pad_off, trial.cm_per_pixel)
project.trialgroup.lineplot_traj(save_as=analysis_dir / f"{bodypart}_all_traj_with_beha_zones.svg", Beha=behavior_obj)

Lineplot all valid traj

In [ ]:
project.trialgroup.lineplot_traj(save_as=u.make_path(analysis_dir, f"{bodypart}_all_traj.svg"))

Lineplot all valid traj + facet grib per protocol

In [ ]:
project.trialgroup.lineplot_traj_per_indentity(save_as=analysis_dir / f"{bodypart}_traj_per_indentity.svg")

## Dstribution analysis (scalar metrics)

In [ ]:
metrics = [
    "avg_velocity_laser_period", 
    "tortuosity_laser_period", 
    "tortuosity_pad_to_lever", 
]

In [ ]:
comparisons = [
    # Conti vs Beta
    ("Conti_LaserOff.low",  "Beta_LaserOff.low"),
    ("Conti_LaserOff.high", "Beta_LaserOff.high"),
    ("Conti_LaserOn.low",   "Beta_LaserOn.low"),
    ("Conti_LaserOn.high",  "Beta_LaserOn.high"),

    # Off vs On
    ("Conti_LaserOff.low",  "Conti_LaserOn.low"),
    ("Conti_LaserOff.high", "Conti_LaserOn.high"),
    ("Beta_LaserOff.low",   "Beta_LaserOn.low"),
    ("Beta_LaserOff.high",  "Beta_LaserOn.high"),

    # low vs high
    ("Beta_LaserOff.low",   "Beta_LaserOff.high"),
    ("Beta_LaserOn.low",    "Beta_LaserOn.high"),
    ("Conti_LaserOff.low",  "Conti_LaserOff.high"),
    ("Conti_LaserOn.low",   "Conti_LaserOn.high"),
]

In [ ]:
for metric in metrics: 
    project.trialgroup.violin_statistic(comparisons, metric=metric, 
                                     save_as=u.make_path(analysis_dir / "distribution" / bodypart, f"{metric}.svg"))

Laser Off merged

In [ ]:
comparisons_merge_Off = [
    # conti vs beta
    ("Conti.low",  "Beta.low"),
    ("Conti.high", "Beta.high"),

    # low vs high
    ("LaserOff.high", "Conti.high"),
    ("LaserOff.high",  "Beta.high"),
    ("LaserOff.low",    "Beta.low"),
    ("LaserOff.low",   "Conti.low"),

    # condition high vs condition low
    ("Conti.low", "Conti.high"),
    ("Beta.low",  "Beta.high"),

    # Beta high ON vs Conti low ON 
    # (because conti low is suppose to be as damagefull as the beta high)
    ("Beta.high", "Conti.low"),
    ("Beta.low", "Conti.high")
]

In [ ]:
for metric in metrics: 
    project.trialgroup.violin_statistic(comparisons_merge_Off, metric=metric,  merge_Off=True,
                                     save_as=u.make_path(analysis_dir / "distribution" / bodypart, f"{metric}_merged_off.svg"),
                                     order=["LaserOff", "Conti", "Beta"])

## Single traj timeseries analysis

In [ ]:
for trial in tqdm(project.trialgroup.trials, desc="plotting timeseries"): 
    if not trial.is_valid(): 
        continue
    
    traj: TrajectoryDLC = trial.trajectories.get(bodypart)

    if not traj.is_valid(): 
        continue

    fig, ax = plt.subplots()

    ax = traj.plot_traj(traj.coords, ax, fig, color = "orange", label="raw")
    ax = traj.plot_traj(traj.interpolated_coords, ax, fig, color = "green", label="interpolated")
    ax = traj.plot_traj(traj.clean_coords, ax, fig, color = "blue", label="clean")


    name = trial.name
    title = name[:len(name)//2] + "\n" + name[len(name)//2:]

    ax.set(
        title=title,
        xlabel="X position (cm)",
        ylabel="Y position (cm)",
    )
    fig.savefig(u.make_path(analysis_dir / "traj_per_trial" / bodypart, f"{trial.name}.svg"))
    plt.close()

    for val in timeseries_metric: 

        traj.plot_tendency(value=val, time_pad_off=trial.time_pad_off,
                           laser_state=trial.laser_state,
                           group=trial.group,
                           show_angle= val == "angle",
                           save_as=u.make_path(analysis_dir / "tendency_per_trial" / bodypart / trial.name , f"{val}.svg"))